# Generated by Django 5.2.4 on 2025-09-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0003_client_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("can_manage_clients", "Может управлять клиентами")]
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_manage_mailings", "Может управлять рассылками")]
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_manage_messages", "Может управлять сообщениями")]
            },
        ),
    ]
